### ISSUE TITLE
希望能接入wandb的训练日志

### ISSUE THREAD

**Issue by petercham** [7eu7d7/HCP-Diffusion#14]
https://wandb.ai/
在配置文件里面填写上appkey，配置测试图的Prompt文件路径，自动每隔多少步出一张测试图

**Comment by 7eu7d7** [comment]
wandb login之后，在logger模块中添加 hcpdiff.loggers.WanDBLogger 即可

logger:
  -
    _target_: hcpdiff.loggers.CLILogger
    _partial_: True
    out_path: 'train.log'
    log_step: 20
  - _target_: hcpdiff.loggers.WanDBLogger
    _partial_: True
    log_step: 5
