### ISSUE TITLE
linux support

### ISSUE THREAD

**Issue by pengpengzi** [7eu7d7/HCP-Diffusion#27]
希望能支持linux训练

**Comment by RuaYiii** [comment]
> 希望能支持linux训练

不应该是支持window训练吗 , linux训练应该纯没问题吧

**Comment by pengpengzi** [comment]
> > 希望能支持linux训练
> 
> 不应该是支持window训练吗 , linux训练应该纯没问题吧

他这readme一大页不都是win的命令行教程
