### ISSUE TITLE
采用默认配置训练速度慢accelerate launch -m hcpdiff.train_ac_single

### ISSUE THREAD

**Issue by EvilBT** [7eu7d7/HCP-Diffusion#34]
大佬我在使用默认指令在训练lora时，发现速度很慢：accelerate launch -m hcpdiff.train_ac_single --cfg cfgs/train/examples/lora_conventional.yaml --model.pretrained_model_name_or_path "C://res/meta" dataset_dir="C://res/data/train"

打开任务管理器发现Cuda使用率一阵一阵的，这里是我哪里配置有问题吗，我的配置是3090 24G ,Windows 10

![QQ图片20230903044522](https://github.com/7eu7d7/HCP-Diffusion/assets/8469484/afdd8004-efc6-4c7e-bac4-35e843fa2af5)

**Comment by 7eu7d7** [comment]
windows的数据加载有点问题，在data_source下面添加repeat: 1000可以解决这个问题

**Comment by EvilBT** [comment]
昨晚跑了之后，感觉什么都没到，这里会是哪里的问题呢
