### ISSUE TITLE
无法通过 JsonCaptionLoader 正确加载由 gen_from_ptlist 脚本生成的 caption

### ISSUE THREAD

**Issue by frimin** [7eu7d7/HCP-Diffusion#42]
gen_from_ptlist 生成的 json key带文件扩展名。TXTCaptionLoader 加载的时候默认剔除了文件扩展名。JsonCaptionLoader / YamlCaptionLoader没有剔除文件扩展名。

各个模块似乎没有统一带不带扩展名。

**Comment by 7eu7d7** [comment]
bug fix in new verision
